import './globals.css';
import 'public/css/style.css';
import 'public/css/content.css';
import Link from 'next/link';
import Nav from './component/Nav';
import Nav from './component/Footer';
import AuthSession from "./component/AuthSession";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faBreadSlice } from "@fortawesome/free-solid-svg-icons";
import { BsSearch } from "react-icons/bs"
// import { library } from "@fortawesome/fontawesome-svg-core";
// import { faStar as farFaStar } from "@fortawesome/free-regular-svg-icons";
// import { faStar as fasFaStar } from "@fortawesome/free-solid-svg-icons";
// library.add(farFaStar, fasFaStar)

export const metadata = {
  title: 'WEB',
  description: 'Generated by hyunj',
}

export default function RootLayout({ children }) {
    
  return (
    <html>
      <body>
      <AuthSession>
        <div className="site-container">
          <Nav></Nav>
          {children}
          <Footer></Footer>
        </div>
      </AuthSession>
      </body>
    </html>
  )
}
